// ============================================
// PRODUCT CATEGORIES SEEDER - 300+ Categories
// Based on the comprehensive prompt
// Arabic + English for each category
// ============================================

export const productCategories = [
  // ============================================
  // 1. TEXTUAL CONTENT (المحتوى النصي والمكتوب)
  // ============================================

  // 1.1 E-Books (الكتب الإلكترونية) - 46 types
  {
    nameAr: 'كتب إلكترونية علمية',
    nameEn: 'Scientific E-Books',
    slug: 'ebook-scientific',
    parentId: null,
    order: 1,
  },
  {
    nameAr: 'كتب إلكترونية للأطفال',
    nameEn: 'Children E-Books',
    slug: 'ebook-children',
    parentId: null,
    order: 2,
  },
  {
    nameAr: 'كتب تطوير الذات',
    nameEn: 'Self-Development E-Books',
    slug: 'ebook-self-development',
    parentId: null,
    order: 3,
  },
  {
    nameAr: 'كتب السيرة الذاتية',
    nameEn: 'Biography E-Books',
    slug: 'ebook-biography',
    parentId: null,
    order: 4,
  },
  {
    nameAr: 'كتب التاريخ',
    nameEn: 'History E-Books',
    slug: 'ebook-history',
    parentId: null,
    order: 5,
  },
  {
    nameAr: 'كتب الجغرافيا',
    nameEn: 'Geography E-Books',
    slug: 'ebook-geography',
    parentId: null,
    order: 6,
  },
  {
    nameAr: 'كتب العلوم الطبيعية',
    nameEn: 'Natural Sciences E-Books',
    slug: 'ebook-natural-sciences',
    parentId: null,
    order: 7,
  },
  {
    nameAr: 'كتب العلوم الاجتماعية',
    nameEn: 'Social Sciences E-Books',
    slug: 'ebook-social-sciences',
    parentId: null,
    order: 8,
  },
  {
    nameAr: 'كتب الأعمال والاقتصاد',
    nameEn: 'Business & Economics E-Books',
    slug: 'ebook-business-economics',
    parentId: null,
    order: 9,
  },
  {
    nameAr: 'كتب الدين والفلسفة',
    nameEn: 'Religion & Philosophy E-Books',
    slug: 'ebook-religion-philosophy',
    parentId: null,
    order: 10,
  },
  {
    nameAr: 'كتب الفنون والحرف',
    nameEn: 'Arts & Crafts E-Books',
    slug: 'ebook-arts-crafts',
    parentId: null,
    order: 11,
  },
  {
    nameAr: 'كتب الموضة والجمال',
    nameEn: 'Fashion & Beauty E-Books',
    slug: 'ebook-fashion-beauty',
    parentId: null,
    order: 12,
  },
  {
    nameAr: 'كتب الطبخ والطعام',
    nameEn: 'Cooking & Food E-Books',
    slug: 'ebook-cooking-food',
    parentId: null,
    order: 13,
  },
  {
    nameAr: 'كتب الصحة والطب',
    nameEn: 'Health & Medicine E-Books',
    slug: 'ebook-health-medicine',
    parentId: null,
    order: 14,
  },
  {
    nameAr: 'كتب التكنولوجيا',
    nameEn: 'Technology E-Books',
    slug: 'ebook-technology',
    parentId: null,
    order: 15,
  },
  {
    nameAr: 'كتب السفر والسياحة',
    nameEn: 'Travel & Tourism E-Books',
    slug: 'ebook-travel-tourism',
    parentId: null,
    order: 16,
  },
  {
    nameAr: 'كتب التعليم',
    nameEn: 'Education E-Books',
    slug: 'ebook-education',
    parentId: null,
    order: 17,
  },
  {
    nameAr: 'كتب الرياضة',
    nameEn: 'Sports E-Books',
    slug: 'ebook-sports',
    parentId: null,
    order: 18,
  },
  {
    nameAr: 'كتب القانون',
    nameEn: 'Law E-Books',
    slug: 'ebook-law',
    parentId: null,
    order: 19,
  },
  {
    nameAr: 'كتب البيئة',
    nameEn: 'Environment E-Books',
    slug: 'ebook-environment',
    parentId: null,
    order: 20,
  },
  {
    nameAr: 'كتب مرجعية',
    nameEn: 'Reference E-Books',
    slug: 'ebook-reference',
    parentId: null,
    order: 21,
  },
  {
    nameAr: 'روايات خيالية',
    nameEn: 'Fiction Novels',
    slug: 'ebook-fiction-novel',
    parentId: null,
    order: 22,
  },
  {
    nameAr: 'الأدب الكلاسيكي',
    nameEn: 'Classic Literature',
    slug: 'ebook-classic-literature',
    parentId: null,
    order: 23,
  },
  {
    nameAr: 'قصص قصيرة',
    nameEn: 'Short Stories',
    slug: 'ebook-short-stories',
    parentId: null,
    order: 24,
  },
  {
    nameAr: 'روايات مصورة',
    nameEn: 'Graphic Novels',
    slug: 'ebook-graphic-novel',
    parentId: null,
    order: 25,
  },
  {
    nameAr: 'مسرحيات',
    nameEn: 'Plays',
    slug: 'ebook-plays',
    parentId: null,
    order: 26,
  },
  {
    nameAr: 'شعر',
    nameEn: 'Poetry',
    slug: 'ebook-poetry',
    parentId: null,
    order: 27,
  },
  {
    nameAr: 'أساطير',
    nameEn: 'Mythology',
    slug: 'ebook-mythology',
    parentId: null,
    order: 28,
  },

  // 1.2 Research & Reports (الأبحاث والتقارير) - 7 types
  {
    nameAr: 'أبحاث السوق',
    nameEn: 'Market Research',
    slug: 'market-research',
    parentId: null,
    order: 29,
  },
  {
    nameAr: 'تقارير صناعية',
    nameEn: 'Industry Reports',
    slug: 'industry-report',
    parentId: null,
    order: 30,
  },
  {
    nameAr: 'دراسات الجدوى',
    nameEn: 'Feasibility Studies',
    slug: 'feasibility-study',
    parentId: null,
    order: 31,
  },
  {
    nameAr: 'أوراق بيضاء',
    nameEn: 'White Papers',
    slug: 'white-paper',
    parentId: null,
    order: 32,
  },
  {
    nameAr: 'دراسات حالة',
    nameEn: 'Case Studies',
    slug: 'case-study',
    parentId: null,
    order: 33,
  },
  {
    nameAr: 'تقارير إحصائية',
    nameEn: 'Statistical Reports',
    slug: 'statistical-report',
    parentId: null,
    order: 34,
  },
  {
    nameAr: 'أبحاث علمية',
    nameEn: 'Scientific Research',
    slug: 'scientific-research',
    parentId: null,
    order: 35,
  },

  // 1.3 Text Templates (قوالب نصية) - 10 types
  {
    nameAr: 'قوالب السيرة الذاتية',
    nameEn: 'CV Templates',
    slug: 'template-cv',
    parentId: null,
    order: 36,
  },
  {
    nameAr: 'قوالب الخطابات',
    nameEn: 'Letter Templates',
    slug: 'template-letter',
    parentId: null,
    order: 37,
  },
  {
    nameAr: 'قوالب خطط الأعمال',
    nameEn: 'Business Plan Templates',
    slug: 'template-business-plan',
    parentId: null,
    order: 38,
  },
  {
    nameAr: 'قوالب العقود',
    nameEn: 'Contract Templates',
    slug: 'template-contract',
    parentId: null,
    order: 39,
  },
  {
    nameAr: 'قوالب التسويق',
    nameEn: 'Marketing Templates',
    slug: 'template-marketing',
    parentId: null,
    order: 40,
  },
  {
    nameAr: 'قوالب البريد الإلكتروني',
    nameEn: 'Email Templates',
    slug: 'template-email',
    parentId: null,
    order: 41,
  },
  {
    nameAr: 'قوالب الفواتير',
    nameEn: 'Invoice Templates',
    slug: 'template-invoice',
    parentId: null,
    order: 42,
  },
  {
    nameAr: 'قوالب العروض التقديمية',
    nameEn: 'Presentation Templates',
    slug: 'template-presentation',
    parentId: null,
    order: 43,
  },
  {
    nameAr: 'قوالب المستندات',
    nameEn: 'Document Templates',
    slug: 'template-document',
    parentId: null,
    order: 44,
  },
  {
    nameAr: 'قوالب التقارير',
    nameEn: 'Report Templates',
    slug: 'template-report',
    parentId: null,
    order: 45,
  },

  // 1.4 Educational Content (محتوى تعليمي) - 8 types
  {
    nameAr: 'دورات مكتوبة',
    nameEn: 'Written Courses',
    slug: 'written-course',
    parentId: null,
    order: 46,
  },
  {
    nameAr: 'ملخصات',
    nameEn: 'Summaries',
    slug: 'summary',
    parentId: null,
    order: 47,
  },
  {
    nameAr: 'أدلة وكتيبات',
    nameEn: 'Guides & Manuals',
    slug: 'guide-manual',
    parentId: null,
    order: 48,
  },
  {
    nameAr: 'مقالات ومدونات',
    nameEn: 'Articles & Blogs',
    slug: 'article-blog',
    parentId: null,
    order: 49,
  },
  {
    nameAr: 'ملفات تعليمية',
    nameEn: 'Educational Files',
    slug: 'educational-file',
    parentId: null,
    order: 50,
  },
  {
    nameAr: 'أوراق عمل',
    nameEn: 'Worksheets',
    slug: 'worksheet',
    parentId: null,
    order: 51,
  },
  {
    nameAr: 'اختبارات وكويزات',
    nameEn: 'Quizzes & Tests',
    slug: 'quiz-test',
    parentId: null,
    order: 52,
  },
  {
    nameAr: 'ملفات بروم��ت',
    nameEn: 'Prompt Files',
    slug: 'prompt-file',
    parentId: null,
    order: 53,
  },

  // ============================================
  // 2. VISUAL CONTENT (المحتوى المرئي البصري)
  // ============================================

  // 2.1 Design Templates (قوالب التصميم) - 8 types
  {
    nameAr: 'قوالب Canva',
    nameEn: 'Canva Templates',
    slug: 'template-canva',
    parentId: null,
    order: 54,
  },
  {
    nameAr: 'قوالب Photoshop',
    nameEn: 'Photoshop Templates',
    slug: 'template-photoshop',
    parentId: null,
    order: 55,
  },
  {
    nameAr: 'قوالب Illustrator',
    nameEn: 'Illustrator Templates',
    slug: 'template-illustrator',
    parentId: null,
    order: 56,
  },
  {
    nameAr: 'قوالب InDesign',
    nameEn: 'InDesign Templates',
    slug: 'template-indesign',
    parentId: null,
    order: 57,
  },
  {
    nameAr: 'قوالب Figma',
    nameEn: 'Figma Templates',
    slug: 'template-figma',
    parentId: null,
    order: 58,
  },
  {
    nameAr: 'قوالب Sketch',
    nameEn: 'Sketch Templates',
    slug: 'template-sketch',
    parentId: null,
    order: 59,
  },
  {
    nameAr: 'قوالب After Effects',
    nameEn: 'After Effects Templates',
    slug: 'template-after-effects',
    parentId: null,
    order: 60,
  },
  {
    nameAr: 'قوالب Premiere',
    nameEn: 'Premiere Templates',
    slug: 'template-premiere',
    parentId: null,
    order: 61,
  },

  // 2.2 Images & Graphics (الصور والرسوم) - 13 types
  {
    nameAr: 'صور مخزنة',
    nameEn: 'Stock Photos',
    slug: 'stock-photo',
    parentId: null,
    order: 62,
  },
  {
    nameAr: 'رسوم توضيحية',
    nameEn: 'Illustrations',
    slug: 'illustration',
    parentId: null,
    order: 63,
  },
  {
    nameAr: 'مجموعات أيقونات',
    nameEn: 'Icon Sets',
    slug: 'icon-set',
    parentId: null,
    order: 64,
  },
  {
    nameAr: 'شخصيات كرتونية',
    nameEn: 'Cartoon Characters',
    slug: 'character-cartoon',
    parentId: null,
    order: 65,
  },
  {
    nameAr: 'فن رقمي',
    nameEn: 'Digital Art',
    slug: 'digital-art',
    parentId: null,
    order: 66,
  },
  {
    nameAr: 'إنفوجرافيك',
    nameEn: 'Infographics',
    slug: 'infographic',
    parentId: null,
    order: 67,
  },
  {
    nameAr: 'مخططات ورسوم بيانية',
    nameEn: 'Charts & Graphs',
    slug: 'chart-graph',
    parentId: null,
    order: 68,
  },
  {
    nameAr: 'خلفيات وورق جدران',
    nameEn: 'Backgrounds & Wallpapers',
    slug: 'background-wallpaper',
    parentId: null,
    order: 69,
  },
  {
    nameAr: 'أنماط وأنسجة',
    nameEn: 'Patterns & Textures',
    slug: 'pattern-texture',
    parentId: null,
    order: 70,
  },
  {
    nameAr: 'ملصقات رقمية',
    nameEn: 'Digital Stickers',
    slug: 'digital-sticker',
    parentId: null,
    order: 71,
  },
  {
    nameAr: 'صور PNG شفافة',
    nameEn: 'Transparent PNGs',
    slug: 'png-transparent',
    parentId: null,
    order: 72,
  },
  {
    nameAr: 'صور Vector',
    nameEn: 'Vector Images',
    slug: 'vector-image',
    parentId: null,
    order: 73,
  },
  {
    nameAr: 'زخارف وتصاميم',
    nameEn: 'Decoration Designs',
    slug: 'decoration-design',
    parentId: null,
    order: 74,
  },

  // 2.3 Print Designs (تصاميم الطباعة) - 13 types
  {
    nameAr: 'تصاميم تيشيرت',
    nameEn: 'T-Shirt Designs',
    slug: 'print-tshirt',
    parentId: null,
    order: 75,
  },
  {
    nameAr: 'تصاميم أكواب',
    nameEn: 'Mug Designs',
    slug: 'print-mug',
    parentId: null,
    order: 76,
  },
  {
    nameAr: 'تصاميم حقائب',
    nameEn: 'Bag Designs',
    slug: 'print-bag',
    parentId: null,
    order: 77,
  },
  {
    nameAr: 'تصاميم ملصقات',
    nameEn: 'Poster Designs',
    slug: 'print-poster',
    parentId: null,
    order: 78,
  },
  {
    nameAr: 'تصاميم ستيكرز',
    nameEn: 'Sticker Designs',
    slug: 'print-sticker',
    parentId: null,
    order: 79,
  },
  {
    nameAr: 'تصاميم قبعات',
    nameEn: 'Hat Designs',
    slug: 'print-hat',
    parentId: null,
    order: 80,
  },
  {
    nameAr: 'تصاميم وسائد',
    nameEn: 'Pillow Designs',
    slug: 'print-pillow',
    parentId: null,
    order: 81,
  },
  {
    nameAr: 'تصاميم أغطية الهاتف',
    nameEn: 'Phone Case Designs',
    slug: 'print-phone-case',
    parentId: null,
    order: 82,
  },
  {
    nameAr: 'تصاميم لوحات قماشية',
    nameEn: 'Canvas Designs',
    slug: 'print-canvas',
    parentId: null,
    order: 83,
  },
  {
    nameAr: 'تصاميم بطاقات عمل',
    nameEn: 'Business Card Designs',
    slug: 'print-business-card',
    parentId: null,
    order: 84,
  },
  {
    nameAr: 'تصاميم دعوات',
    nameEn: 'Invitation Designs',
    slug: 'print-invitation',
    parentId: null,
    order: 85,
  },
  {
    nameAr: 'تصاميم شهادات',
    nameEn: 'Certificate Designs',
    slug: 'print-certificate',
    parentId: null,
    order: 86,
  },
  {
    nameAr: 'تصاميم بطاقات معايدة',
    nameEn: 'Greeting Card Designs',
    slug: 'print-greeting-card',
    parentId: null,
    order: 87,
  },

  // 2.4 Business Templates (قوالب الأعمال) - 10 types
  {
    nameAr: 'قوالب الشعارات',
    nameEn: 'Logo Templates',
    slug: 'template-logo',
    parentId: null,
    order: 88,
  },
  {
    nameAr: 'قوالب هوية بصرية',
    nameEn: 'Brand Identity Templates',
    slug: 'template-brand-identity',
    parentId: null,
    order: 89,
  },
  {
    nameAr: 'قوالب منشورات السوشال ميديا',
    nameEn: 'Social Media Post Templates',
    slug: 'template-social-media',
    parentId: null,
    order: 90,
  },
  {
    nameAr: 'قوالب كتيبات',
    nameEn: 'Brochure Templates',
    slug: 'template-brochure',
    parentId: null,
    order: 91,
  },
  {
    nameAr: 'قوالب كتالوج',
    nameEn: 'Catalog Templates',
    slug: 'template-catalog',
    parentId: null,
    order: 92,
  },
  {
    nameAr: 'قوالب ميديا كيت',
    nameEn: 'Media Kit Templates',
    slug: 'template-media-kit',
    parentId: null,
    order: 93,
  },
  {
    nameAr: 'قوالب بوسترات إعلانية',
    nameEn: 'Ad Poster Templates',
    slug: 'template-ad-poster',
    parentId: null,
    order: 94,
  },
  {
    nameAr: 'قوالب منيو مطاعم',
    nameEn: 'Restaurant Menu Templates',
    slug: 'template-menu',
    parentId: null,
    order: 95,
  },
  {
    nameAr: 'قوالب بطاقات منتجات',
    nameEn: 'Product Card Templates',
    slug: 'template-product-card',
    parentId: null,
    order: 96,
  },
  {
    nameAr: 'قوالب لافتات',
    nameEn: 'Banner Templates',
    slug: 'template-banner',
    parentId: null,
    order: 97,
  },

  // 2.5 Design Resources (موارد التصميم) - 10 types
  {
    nameAr: 'خطوط رقمية',
    nameEn: 'Digital Fonts',
    slug: 'font-digital',
    parentId: null,
    order: 98,
  },
  {
    nameAr: 'فرش Photoshop',
    nameEn: 'Photoshop Brushes',
    slug: 'brush-photoshop',
    parentId: null,
    order: 99,
  },
  {
    nameAr: 'فلاتر وإجراءات',
    nameEn: 'Filters & Actions',
    slug: 'filter-action',
    parentId: null,
    order: 100,
  },
  {
    nameAr: 'ألوان وباليتات',
    nameEn: 'Color Palettes',
    slug: 'color-palette',
    parentId: null,
    order: 101,
  },
  {
    nameAr: 'موك آب',
    nameEn: 'Mockups',
    slug: 'mockup',
    parentId: null,
    order: 102,
  },
  {
    nameAr: 'نماذج ثلاثية الأبعاد',
    nameEn: '3D Models',
    slug: 'model-3d',
    parentId: null,
    order: 103,
  },
  {
    nameAr: 'خرائط ذهنية',
    nameEn: 'Mind Maps',
    slug: 'mind-map',
    parentId: null,
    order: 104,
  },
  {
    nameAr: 'أنظمة تصميم',
    nameEn: 'Design Systems',
    slug: 'design-system',
    parentId: null,
    order: 105,
  },
  {
    nameAr: 'كيت UI',
    nameEn: 'UI Kits',
    slug: 'ui-kit',
    parentId: null,
    order: 106,
  },
  {
    nameAr: 'موارد تصميم متنوعة',
    nameEn: 'Miscellaneous Design Resources',
    slug: 'design-resource-misc',
    parentId: null,
    order: 107,
  },

  // ============================================
  // 3. AUDIO CONTENT (المحتوى الصوتي)
  // ============================================

  // 3.1 Music (موسيقى) - 12 types
  {
    nameAr: 'موسيقى خلفية',
    nameEn: 'Background Music',
    slug: 'music-background',
    parentId: null,
    order: 108,
  },
  {
    nameAr: 'موسيقى للفيديو',
    nameEn: 'Video Music',
    slug: 'music-video',
    parentId: null,
    order: 109,
  },
  {
    nameAr: 'موسيقى بودكاست',
    nameEn: 'Podcast Music',
    slug: 'music-podcast',
    parentId: null,
    order: 110,
  },
  {
    nameAr: 'موسيقى ألعاب',
    nameEn: 'Game Music',
    slug: 'music-game',
    parentId: null,
    order: 111,
  },
  {
    nameAr: 'موسيقى حماسية',
    nameEn: 'Motivational Music',
    slug: 'music-motivational',
    parentId: null,
    order: 112,
  },
  {
    nameAr: 'موسيقى هادئة',
    nameEn: 'Calm Music',
    slug: 'music-calm',
    parentId: null,
    order: 113,
  },
  {
    nameAr: 'موسيقى الكترونية',
    nameEn: 'Electronic Music',
    slug: 'music-electronic',
    parentId: null,
    order: 114,
  },
  {
    nameAr: 'موسيقى كلاسيكية',
    nameEn: 'Classical Music',
    slug: 'music-classical',
    parentId: null,
    order: 115,
  },
  {
    nameAr: 'موسيقى لوفي',
    nameEn: 'Lo-Fi Music',
    slug: 'music-lofi',
    parentId: null,
    order: 116,
  },
  {
    nameAr: 'مقطوعات موسيقية',
    nameEn: 'Musical Compositions',
    slug: 'music-composition',
    parentId: null,
    order: 117,
  },
  {
    nameAr: 'موسيقى تصويرية',
    nameEn: 'Cinematic Music',
    slug: 'music-cinematic',
    parentId: null,
    order: 118,
  },
  {
    nameAr: 'موسيقى محيطية',
    nameEn: 'Ambient Music',
    slug: 'music-ambient',
    parentId: null,
    order: 119,
  },

  // 3.2 Sound Effects (مؤثرات صوتية) - 6 types
  {
    nameAr: 'مؤثرات صوتية للفيديو',
    nameEn: 'Video Sound Effects',
    slug: 'sfx-video',
    parentId: null,
    order: 120,
  },
  {
    nameAr: 'مؤثرات صوتية للألعاب',
    nameEn: 'Game Sound Effects',
    slug: 'sfx-game',
    parentId: null,
    order: 121,
  },
  {
    nameAr: 'أصوات البيئة',
    nameEn: 'Environmental Sounds',
    slug: 'sound-environment',
    parentId: null,
    order: 122,
  },
  {
    nameAr: 'أصوات الحيوانات',
    nameEn: 'Animal Sounds',
    slug: 'sound-animal',
    parentId: null,
    order: 123,
  },
  {
    nameAr: 'أصوات التكنولوجيا',
    nameEn: 'Technology Sounds',
    slug: 'sound-technology',
    parentId: null,
    order: 124,
  },
  {
    nameAr: 'أصوات متنوعة',
    nameEn: 'Miscellaneous Sounds',
    slug: 'sound-misc',
    parentId: null,
    order: 125,
  },

  // 3.3 Educational Audio (صوتيات تعليمية) - 3 types
  {
    nameAr: 'كتب صوتية',
    nameEn: 'Audiobooks',
    slug: 'audiobook',
    parentId: null,
    order: 126,
  },
  {
    nameAr: 'دورات صوتية',
    nameEn: 'Audio Courses',
    slug: 'audio-course',
    parentId: null,
    order: 127,
  },
  {
    nameAr: 'ملفات بودكاست',
    nameEn: 'Podcast Episodes',
    slug: 'podcast-episode',
    parentId: null,
    order: 128,
  },

  // ============================================
  // 4. VIDEO CONTENT (المحتوى المرئي المتحرك)
  // ============================================

  // 4.1 Video Footage (لقطات فيديو) - 8 types
  {
    nameAr: 'لقطات فيديو مخزنة',
    nameEn: 'Stock Video Footage',
    slug: 'footage-stock',
    parentId: null,
    order: 129,
  },
  {
    nameAr: 'لقطات الطبيعة',
    nameEn: 'Nature Footage',
    slug: 'footage-nature',
    parentId: null,
    order: 130,
  },
  {
    nameAr: 'لقطات المدن',
    nameEn: 'City Footage',
    slug: 'footage-city',
    parentId: null,
    order: 131,
  },
  {
    nameAr: 'لقطات الأشخاص',
    nameEn: 'People Footage',
    slug: 'footage-people',
    parentId: null,
    order: 132,
  },
  {
    nameAr: 'لقطات الأعمال',
    nameEn: 'Business Footage',
    slug: 'footage-business',
    parentId: null,
    order: 133,
  },
  {
    nameAr: 'لقطات طائرة بدون طيار',
    nameEn: 'Drone Footage',
    slug: 'footage-drone',
    parentId: null,
    order: 134,
  },
  {
    nameAr: 'لقطات تايم لابس',
    nameEn: 'Time-Lapse Footage',
    slug: 'footage-timelapse',
    parentId: null,
    order: 135,
  },
  {
    nameAr: 'لقطات بطيئة',
    nameEn: 'Slow-Motion Footage',
    slug: 'footage-slowmotion',
    parentId: null,
    order: 136,
  },

  // 4.2 Video Templates (قوالب فيديو) - 10 types
  {
    nameAr: 'قوالب موشن جرافيك',
    nameEn: 'Motion Graphics Templates',
    slug: 'template-motion-graphics',
    parentId: null,
    order: 137,
  },
  {
    nameAr: 'قوالب انترو وأوترو',
    nameEn: 'Intro & Outro Templates',
    slug: 'template-intro-outro',
    parentId: null,
    order: 138,
  },
  {
    nameAr: 'قوالب لوغو أنيميشن',
    nameEn: 'Logo Animation Templates',
    slug: 'template-logo-animation',
    parentId: null,
    order: 139,
  },
  {
    nameAr: 'قوالب شرائح السفلى',
    nameEn: 'Lower Third Templates',
    slug: 'template-lower-third',
    parentId: null,
    order: 140,
  },
  {
    nameAr: 'قوالب تيتراشن',
    nameEn: 'Title Templates',
    slug: 'template-title',
    parentId: null,
    order: 141,
  },
  {
    nameAr: 'قوالب انتقالات',
    nameEn: 'Transition Templates',
    slug: 'template-transition',
    parentId: null,
    order: 142,
  },
  {
    nameAr: 'قوالب إعلانات',
    nameEn: 'Ad Templates',
    slug: 'template-ad',
    parentId: null,
    order: 143,
  },
  {
    nameAr: 'قوالب ريلز وشورتس',
    nameEn: 'Reels & Shorts Templates',
    slug: 'template-reels-shorts',
    parentId: null,
    order: 144,
  },
  {
    nameAr: 'قوالب عروض شرائح',
    nameEn: 'Slideshow Templates',
    slug: 'template-slideshow',
    parentId: null,
    order: 145,
  },
  {
    nameAr: 'قوالب فيديو تفسيري',
    nameEn: 'Explainer Video Templates',
    slug: 'template-explainer',
    parentId: null,
    order: 146,
  },

  // 4.3 Educational Videos (فيديوهات تعليمية) - 6 types
  {
    nameAr: 'كورسات فيديو',
    nameEn: 'Video Courses',
    slug: 'video-course',
    parentId: null,
    order: 147,
  },
  {
    nameAr: 'دروس مسجلة',
    nameEn: 'Recorded Lessons',
    slug: 'video-lesson',
    parentId: null,
    order: 148,
  },
  {
    nameAr: 'توتوريال',
    nameEn: 'Tutorials',
    slug: 'video-tutorial',
    parentId: null,
    order: 149,
  },
  {
    nameAr: 'محاضرات',
    nameEn: 'Lectures',
    slug: 'video-lecture',
    parentId: null,
    order: 150,
  },
  {
    nameAr: 'ورش عمل مسجلة',
    nameEn: 'Recorded Workshops',
    slug: 'video-workshop',
    parentId: null,
    order: 151,
  },
  {
    nameAr: 'ويبينار',
    nameEn: 'Webinars',
    slug: 'video-webinar',
    parentId: null,
    order: 152,
  },

  // 4.4 Animation & VFX (رسوم متحركة ومؤثرات) - 7 types
  {
    nameAr: 'رسوم متحركة ثنائية الأبعاد',
    nameEn: '2D Animations',
    slug: 'animation-2d',
    parentId: null,
    order: 153,
  },
  {
    nameAr: 'رسوم متحركة ثلاثية الأبعاد',
    nameEn: '3D Animations',
    slug: 'animation-3d',
    parentId: null,
    order: 154,
  },
  {
    nameAr: 'وايتبورد أنيميشن',
    nameEn: 'Whiteboard Animations',
    slug: 'animation-whiteboard',
    parentId: null,
    order: 155,
  },
  {
    nameAr: 'شخصيات متحركة',
    nameEn: 'Character Animations',
    slug: 'animation-character',
    parentId: null,
    order: 156,
  },
  {
    nameAr: 'مؤثرات بصرية',
    nameEn: 'Visual Effects (VFX)',
    slug: 'vfx',
    parentId: null,
    order: 157,
  },
  {
    nameAr: 'جرين سكرين',
    nameEn: 'Green Screen Effects',
    slug: 'greenscreen-effect',
    parentId: null,
    order: 158,
  },
  {
    nameAr: 'باجرات متحركة',
    nameEn: 'Animated Overlays',
    slug: 'animated-overlay',
    parentId: null,
    order: 159,
  },

  // ============================================
  // 5. INTERACTIVE CONTENT (المحتوى التفاعلي)
  // ============================================

  // 5.1 Games (ألعاب) - 8 types
  {
    nameAr: 'ألعاب موبايل',
    nameEn: 'Mobile Games',
    slug: 'game-mobile',
    parentId: null,
    order: 160,
  },
  {
    nameAr: 'ألعاب ويب',
    nameEn: 'Web Games',
    slug: 'game-web',
    parentId: null,
    order: 161,
  },
  {
    nameAr: 'ألعاب Unity',
    nameEn: 'Unity Games',
    slug: 'game-unity',
    parentId: null,
    order: 162,
  },
  {
    nameAr: 'ألعاب Unreal Engine',
    nameEn: 'Unreal Engine Games',
    slug: 'game-unreal',
    parentId: null,
    order: 163,
  },
  {
    nameAr: 'أكواد ألعاب جاهزة',
    nameEn: 'Game Source Codes',
    slug: 'game-source-code',
    parentId: null,
    order: 164,
  },
  {
    nameAr: 'كيتات ألعاب',
    nameEn: 'Game Kits',
    slug: 'game-kit',
    parentId: null,
    order: 165,
  },
  {
    nameAr: 'أسيتات ألعاب',
    nameEn: 'Game Assets',
    slug: 'game-asset',
    parentId: null,
    order: 166,
  },
  {
    nameAr: 'ألعاب تعليمية',
    nameEn: 'Educational Games',
    slug: 'game-educational',
    parentId: null,
    order: 167,
  },

  // 5.2 Apps (تطبيقات) - 6 types
  {
    nameAr: 'تطبيقات موبايل جاهزة',
    nameEn: 'Ready Mobile Apps',
    slug: 'app-mobile-ready',
    parentId: null,
    order: 168,
  },
  {
    nameAr: 'أكواد تطبيقات',
    nameEn: 'App Source Codes',
    slug: 'app-source-code',
    parentId: null,
    order: 169,
  },
  {
    nameAr: 'قوالب تطبيقات',
    nameEn: 'App Templates',
    slug: 'app-template',
    parentId: null,
    order: 170,
  },
  {
    nameAr: 'ملحقات تطبيقات',
    nameEn: 'App Plugins',
    slug: 'app-plugin',
    parentId: null,
    order: 171,
  },
  {
    nameAr: 'تطبيقات React Native',
    nameEn: 'React Native Apps',
    slug: 'app-react-native',
    parentId: null,
    order: 172,
  },
  {
    nameAr: 'تطبيقات Flutter',
    nameEn: 'Flutter Apps',
    slug: 'app-flutter',
    parentId: null,
    order: 173,
  },

  // 5.3 Interactive Media (وسائط تفاعلية) - 6 types
  {
    nameAr: 'كويزات تفاعلية',
    nameEn: 'Interactive Quizzes',
    slug: 'interactive-quiz',
    parentId: null,
    order: 174,
  },
  {
    nameAr: 'استطلاعات',
    nameEn: 'Surveys',
    slug: 'interactive-survey',
    parentId: null,
    order: 175,
  },
  {
    nameAr: 'عروض تفاعلية',
    nameEn: 'Interactive Presentations',
    slug: 'interactive-presentation',
    parentId: null,
    order: 176,
  },
  {
    nameAr: 'كتب تفاعلية',
    nameEn: 'Interactive Books',
    slug: 'interactive-book',
    parentId: null,
    order: 177,
  },
  {
    nameAr: 'خرائط تفاعلية',
    nameEn: 'Interactive Maps',
    slug: 'interactive-map',
    parentId: null,
    order: 178,
  },
  {
    nameAr: 'انفوجرافيك تفاعلي',
    nameEn: 'Interactive Infographics',
    slug: 'interactive-infographic',
    parentId: null,
    order: 179,
  },

  // ============================================
  // 6. CODE & TECH (البرمجيات والتقنية)
  // ============================================

  // 6.1 Scripts & Codes (سكريبتات وأكواد) - 12 types
  {
    nameAr: 'سكريبت Python',
    nameEn: 'Python Scripts',
    slug: 'script-python',
    parentId: null,
    order: 180,
  },
  {
    nameAr: 'سكريبت JavaScript',
    nameEn: 'JavaScript Scripts',
    slug: 'script-javascript',
    parentId: null,
    order: 181,
  },
  {
    nameAr: 'سكريبت PHP',
    nameEn: 'PHP Scripts',
    slug: 'script-php',
    parentId: null,
    order: 182,
  },
  {
    nameAr: 'سكريبت Node.js',
    nameEn: 'Node.js Scripts',
    slug: 'script-nodejs',
    parentId: null,
    order: 183,
  },
  {
    nameAr: 'سكريبت Automation',
    nameEn: 'Automation Scripts',
    slug: 'script-automation',
    parentId: null,
    order: 184,
  },
  {
    nameAr: 'أكواد ذكاء اصطناعي',
    nameEn: 'AI Code',
    slug: 'code-ai',
    parentId: null,
    order: 185,
  },
  {
    nameAr: 'أكواد Machine Learning',
    nameEn: 'Machine Learning Code',
    slug: 'code-ml',
    parentId: null,
    order: 186,
  },
  {
    nameAr: 'أكواد Blockchain',
    nameEn: 'Blockchain Code',
    slug: 'code-blockchain',
    parentId: null,
    order: 187,
  },
  {
    nameAr: 'أكواد APIs',
    nameEn: 'API Code',
    slug: 'code-api',
    parentId: null,
    order: 188,
  },
  {
    nameAr: 'أكواد Bots',
    nameEn: 'Bot Code',
    slug: 'code-bot',
    parentId: null,
    order: 189,
  },
  {
    nameAr: 'أكواد محولات',
    nameEn: 'Converter Code',
    slug: 'code-converter',
    parentId: null,
    order: 190,
  },
  {
    nameAr: 'أكواد متنوعة',
    nameEn: 'Miscellaneous Code',
    slug: 'code-misc',
    parentId: null,
    order: 191,
  },

  // 6.2 Plugins & Extensions (الإضافات والملحقات) - 10 types
  {
    nameAr: 'إضافات WordPress',
    nameEn: 'WordPress Plugins',
    slug: 'plugin-wordpress',
    parentId: null,
    order: 192,
  },
  {
    nameAr: 'إضافات WooCommerce',
    nameEn: 'WooCommerce Plugins',
    slug: 'plugin-woocommerce',
    parentId: null,
    order: 193,
  },
  {
    nameAr: 'إضافات Shopify',
    nameEn: 'Shopify Plugins',
    slug: 'plugin-shopify',
    parentId: null,
    order: 194,
  },
  {
    nameAr: 'إضافات Chrome',
    nameEn: 'Chrome Extensions',
    slug: 'extension-chrome',
    parentId: null,
    order: 195,
  },
  {
    nameAr: 'إضافات VS Code',
    nameEn: 'VS Code Extensions',
    slug: 'extension-vscode',
    parentId: null,
    order: 196,
  },
  {
    nameAr: 'إضافات Figma',
    nameEn: 'Figma Plugins',
    slug: 'plugin-figma',
    parentId: null,
    order: 197,
  },
  {
    nameAr: 'إضافات Adobe',
    nameEn: 'Adobe Plugins',
    slug: 'plugin-adobe',
    parentId: null,
    order: 198,
  },
  {
    nameAr: 'إضافات Unity',
    nameEn: 'Unity Plugins',
    slug: 'plugin-unity',
    parentId: null,
    order: 199,
  },
  {
    nameAr: 'إضافات Unreal Engine',
    nameEn: 'Unreal Engine Plugins',
    slug: 'plugin-unreal',
    parentId: null,
    order: 200,
  },
  {
    nameAr: 'إضافات متنوعة',
    nameEn: 'Miscellaneous Plugins',
    slug: 'plugin-misc',
    parentId: null,
    order: 201,
  },

  // 6.3 Website Templates (قوالب المواقع) - 11 types
  {
    nameAr: 'قوالب HTML',
    nameEn: 'HTML Templates',
    slug: 'template-html',
    parentId: null,
    order: 202,
  },
  {
    nameAr: 'قوالب WordPress',
    nameEn: 'WordPress Themes',
    slug: 'template-wordpress',
    parentId: null,
    order: 203,
  },
  {
    nameAr: 'قوالب React',
    nameEn: 'React Templates',
    slug: 'template-react',
    parentId: null,
    order: 204,
  },
  {
    nameAr: 'قوالب Next.js',
    nameEn: 'Next.js Templates',
    slug: 'template-nextjs',
    parentId: null,
    order: 205,
  },
  {
    nameAr: 'قوالب Vue.js',
    nameEn: 'Vue.js Templates',
    slug: 'template-vuejs',
    parentId: null,
    order: 206,
  },
  {
    nameAr: 'قوالب Angular',
    nameEn: 'Angular Templates',
    slug: 'template-angular',
    parentId: null,
    order: 207,
  },
  {
    nameAr: 'قوالب Shopify',
    nameEn: 'Shopify Themes',
    slug: 'template-shopify',
    parentId: null,
    order: 208,
  },
  {
    nameAr: 'قوالب متاجر الكترونية',
    nameEn: 'E-commerce Templates',
    slug: 'template-ecommerce',
    parentId: null,
    order: 209,
  },
  {
    nameAr: 'قوالب لاندينغ بيج',
    nameEn: 'Landing Page Templates',
    slug: 'template-landing-page',
    parentId: null,
    order: 210,
  },
  {
    nameAr: 'قوالب بورتفوليو',
    nameEn: 'Portfolio Templates',
    slug: 'template-portfolio',
    parentId: null,
    order: 211,
  },
  {
    nameAr: 'قوالب مدونات',
    nameEn: 'Blog Templates',
    slug: 'template-blog',
    parentId: null,
    order: 212,
  },

  // 6.4 Full Websites (مواقع كاملة) - 5 types
  {
    nameAr: 'مواقع جاهزة',
    nameEn: 'Ready Websites',
    slug: 'website-ready',
    parentId: null,
    order: 213,
  },
  {
    nameAr: 'متاجر الكترونية جاهزة',
    nameEn: 'Ready E-commerce Sites',
    slug: 'website-ecommerce-ready',
    parentId: null,
    order: 214,
  },
  {
    nameAr: 'مواقع نظام إدارة محتوى',
    nameEn: 'CMS Websites',
    slug: 'website-cms',
    parentId: null,
    order: 215,
  },
  {
    nameAr: 'مواقع SaaS',
    nameEn: 'SaaS Websites',
    slug: 'website-saas',
    parentId: null,
    order: 216,
  },
  {
    nameAr: 'مواقع متنوعة',
    nameEn: 'Miscellaneous Websites',
    slug: 'website-misc',
    parentId: null,
    order: 217,
  },

  // 6.5 Software & Tools (برمجيات وأدوات) - 5 types
  {
    nameAr: 'برامج سطح المكتب',
    nameEn: 'Desktop Software',
    slug: 'software-desktop',
    parentId: null,
    order: 218,
  },
  {
    nameAr: 'أدوات سطر الأوامر',
    nameEn: 'CLI Tools',
    slug: 'tool-cli',
    parentId: null,
    order: 219,
  },
  {
    nameAr: 'أدوات تطوير',
    nameEn: 'Developer Tools',
    slug: 'tool-developer',
    parentId: null,
    order: 220,
  },
  {
    nameAr: 'أدوات تسويق',
    nameEn: 'Marketing Tools',
    slug: 'tool-marketing',
    parentId: null,
    order: 221,
  },
  {
    nameAr: 'أدوات متنوعة',
    nameEn: 'Miscellaneous Tools',
    slug: 'tool-misc',
    parentId: null,
    order: 222,
  },

  // ============================================
  // 7. SPECIALIZED DIGITAL (محتوى رقمي متخصص)
  // ============================================

  // 7.1 NFTs & Crypto (NFTs وكربتو) - 6 types
  {
    nameAr: 'فن NFT',
    nameEn: 'NFT Art',
    slug: 'nft-art',
    parentId: null,
    order: 223,
  },
  {
    nameAr: 'NFT مجموعات',
    nameEn: 'NFT Collections',
    slug: 'nft-collection',
    parentId: null,
    order: 224,
  },
  {
    nameAr: 'NFT موسيقى',
    nameEn: 'Music NFTs',
    slug: 'nft-music',
    parentId: null,
    order: 225,
  },
  {
    nameAr: 'عقود ذكية',
    nameEn: 'Smart Contracts',
    slug: 'smart-contract',
    parentId: null,
    order: 226,
  },
  {
    nameAr: 'مشاريع Blockchain',
    nameEn: 'Blockchain Projects',
    slug: 'blockchain-project',
    parentId: null,
    order: 227,
  },
  {
    nameAr: 'محتوى كريبتو متنوع',
    nameEn: 'Miscellaneous Crypto',
    slug: 'crypto-misc',
    parentId: null,
    order: 228,
  },

  // 7.2 3D Assets (أصول ثلاثية الأبعاد) - 8 types
  {
    nameAr: 'نماذج ثلاثية الأبعاد',
    nameEn: '3D Models',
    slug: '3d-model',
    parentId: null,
    order: 229,
  },
  {
    nameAr: 'شخصيات ثلاثية الأبعاد',
    nameEn: '3D Characters',
    slug: '3d-character',
    parentId: null,
    order: 230,
  },
  {
    nameAr: 'بيئات ثلاثية الأبعاد',
    nameEn: '3D Environments',
    slug: '3d-environment',
    parentId: null,
    order: 231,
  },
  {
    nameAr: 'أسيتات ثلاثية الأبعاد',
    nameEn: '3D Assets',
    slug: '3d-asset',
    parentId: null,
    order: 232,
  },
  {
    nameAr: 'خامات ثلاثية الأبعاد',
    nameEn: '3D Materials',
    slug: '3d-material',
    parentId: null,
    order: 233,
  },
  {
    nameAr: 'نسيج ثلاثية الأبعاد',
    nameEn: '3D Textures',
    slug: '3d-texture',
    parentId: null,
    order: 234,
  },
  {
    nameAr: 'ريجنج ثلاثية الأبعاد',
    nameEn: '3D Rigging',
    slug: '3d-rigging',
    parentId: null,
    order: 235,
  },
  {
    nameAr: 'أنيميشن ثلاثية الأبعاد',
    nameEn: '3D Animations',
    slug: '3d-animation',
    parentId: null,
    order: 236,
  },

  // 7.3 VR/AR Content (محتوى الواقع الافتراضي والمعزز) - 6 types
  {
    nameAr: 'تجارب VR',
    nameEn: 'VR Experiences',
    slug: 'vr-experience',
    parentId: null,
    order: 237,
  },
  {
    nameAr: 'ألعاب VR',
    nameEn: 'VR Games',
    slug: 'vr-game',
    parentId: null,
    order: 238,
  },
  {
    nameAr: 'أسيتات VR',
    nameEn: 'VR Assets',
    slug: 'vr-asset',
    parentId: null,
    order: 239,
  },
  {
    nameAr: 'تطبيقات AR',
    nameEn: 'AR Applications',
    slug: 'ar-app',
    parentId: null,
    order: 240,
  },
  {
    nameAr: 'فلاتر AR',
    nameEn: 'AR Filters',
    slug: 'ar-filter',
    parentId: null,
    order: 241,
  },
  {
    nameAr: 'أسيتات AR',
    nameEn: 'AR Assets',
    slug: 'ar-asset',
    parentId: null,
    order: 242,
  },

  // 7.4 Data & Analytics (البيانات والتحليلات) - 5 types
  {
    nameAr: 'قواعد بيانات',
    nameEn: 'Databases',
    slug: 'database',
    parentId: null,
    order: 243,
  },
  {
    nameAr: 'مجموعات بيانات',
    nameEn: 'Datasets',
    slug: 'dataset',
    parentId: null,
    order: 244,
  },
  {
    nameAr: 'أدوات تحليل',
    nameEn: 'Analytics Tools',
    slug: 'analytics-tool',
    parentId: null,
    order: 245,
  },
  {
    nameAr: 'لوحات معلومات',
    nameEn: 'Dashboard Templates',
    slug: 'dashboard-template',
    parentId: null,
    order: 246,
  },
  {
    nameAr: 'تقارير تحليلية',
    nameEn: 'Analytics Reports',
    slug: 'analytics-report',
    parentId: null,
    order: 247,
  },

  // 7.5 Miscellaneous Digital (متفرقات رقمية) - 5 types
  {
    nameAr: 'شهادات رقمية',
    nameEn: 'Digital Certificates',
    slug: 'certificate-digital',
    parentId: null,
    order: 248,
  },
  {
    nameAr: 'تذاكر رقمية',
    nameEn: 'Digital Tickets',
    slug: 'ticket-digital',
    parentId: null,
    order: 249,
  },
  {
    nameAr: 'باركودات',
    nameEn: 'Barcodes & QR Codes',
    slug: 'barcode-qr',
    parentId: null,
    order: 250,
  },
  {
    nameAr: 'صور رمزية',
    nameEn: 'Avatars',
    slug: 'avatar',
    parentId: null,
    order: 251,
  },
  {
    nameAr: 'محتوى رقمي متنوع',
    nameEn: 'Miscellaneous Digital Content',
    slug: 'digital-misc',
    parentId: null,
    order: 252,
  },

  // ============================================
  // 8. SUBSCRIPTION SERVICES (خدمات الاشتراك)
  // ============================================

  // 8.1 Premium Content (محتوى مميز) - 8 types
  {
    nameAr: 'اشتراك محتوى حصري',
    nameEn: 'Exclusive Content Subscription',
    slug: 'subscription-exclusive',
    parentId: null,
    order: 253,
  },
  {
    nameAr: 'اشتراك كورسات',
    nameEn: 'Course Subscription',
    slug: 'subscription-course',
    parentId: null,
    order: 254,
  },
  {
    nameAr: 'اشتراك موسيقى',
    nameEn: 'Music Subscription',
    slug: 'subscription-music',
    parentId: null,
    order: 255,
  },
  {
    nameAr: 'اشتراك فيديوهات',
    nameEn: 'Video Subscription',
    slug: 'subscription-video',
    parentId: null,
    order: 256,
  },
  {
    nameAr: 'اشتراك صور مخزنة',
    nameEn: 'Stock Photo Subscription',
    slug: 'subscription-stock-photo',
    parentId: null,
    order: 257,
  },
  {
    nameAr: 'اشتراك قوالب',
    nameEn: 'Template Subscription',
    slug: 'subscription-template',
    parentId: null,
    order: 258,
  },
  {
    nameAr: 'اشتراك أدوات',
    nameEn: 'Tool Subscription',
    slug: 'subscription-tool',
    parentId: null,
    order: 259,
  },
  {
    nameAr: 'اشتراك مكتبة رقمية',
    nameEn: 'Digital Library Subscription',
    slug: 'subscription-library',
    parentId: null,
    order: 260,
  },

  // 8.2 SaaS Products (منتجات SaaS) - 12 types
  {
    nameAr: 'اشتراك SaaS تسويق',
    nameEn: 'Marketing SaaS',
    slug: 'saas-marketing',
    parentId: null,
    order: 261,
  },
  {
    nameAr: 'اشتراك SaaS تصميم',
    nameEn: 'Design SaaS',
    slug: 'saas-design',
    parentId: null,
    order: 262,
  },
  {
    nameAr: 'اشتراك SaaS إدارة مشاريع',
    nameEn: 'Project Management SaaS',
    slug: 'saas-project-management',
    parentId: null,
    order: 263,
  },
  {
    nameAr: 'اشتراك SaaS محاسبة',
    nameEn: 'Accounting SaaS',
    slug: 'saas-accounting',
    parentId: null,
    order: 264,
  },
  {
    nameAr: 'اشتراك SaaS مبيعات',
    nameEn: 'Sales SaaS',
    slug: 'saas-sales',
    parentId: null,
    order: 265,
  },
  {
    nameAr: 'اشتراك SaaS موارد بشرية',
    nameEn: 'HR SaaS',
    slug: 'saas-hr',
    parentId: null,
    order: 266,
  },
  {
    nameAr: 'اشتراك SaaS تحليلات',
    nameEn: 'Analytics SaaS',
    slug: 'saas-analytics',
    parentId: null,
    order: 267,
  },
  {
    nameAr: 'اشتراك SaaS سوشال ميديا',
    nameEn: 'Social Media SaaS',
    slug: 'saas-social-media',
    parentId: null,
    order: 268,
  },
  {
    nameAr: 'اشتراك SaaS خدمة عملاء',
    nameEn: 'Customer Service SaaS',
    slug: 'saas-customer-service',
    parentId: null,
    order: 269,
  },
  {
    nameAr: 'اشتراك SaaS بريد الكتروني',
    nameEn: 'Email SaaS',
    slug: 'saas-email',
    parentId: null,
    order: 270,
  },
  {
    nameAr: 'اشتراك SaaS تعاون',
    nameEn: 'Collaboration SaaS',
    slug: 'saas-collaboration',
    parentId: null,
    order: 271,
  },
  {
    nameAr: 'اشتراك SaaS متنوع',
    nameEn: 'Miscellaneous SaaS',
    slug: 'saas-misc',
    parentId: null,
    order: 272,
  },

  // ============================================
  // 9. SPECIALIZED PROFESSIONAL (محتوى احترافي متخصص)
  // ============================================

  // 9.1 Medical & Health (طبي وصحي) - 5 types
  {
    nameAr: 'برمجيات طبية',
    nameEn: 'Medical Software',
    slug: 'medical-software',
    parentId: null,
    order: 273,
  },
  {
    nameAr: 'قوالب طبية',
    nameEn: 'Medical Templates',
    slug: 'medical-template',
    parentId: null,
    order: 274,
  },
  {
    nameAr: 'محتوى تعليمي طبي',
    nameEn: 'Medical Educational Content',
    slug: 'medical-educational',
    parentId: null,
    order: 275,
  },
  {
    nameAr: 'تطبيقات صحية',
    nameEn: 'Health Apps',
    slug: 'health-app',
    parentId: null,
    order: 276,
  },
  {
    nameAr: 'أدوات طبية رقمية',
    nameEn: 'Digital Medical Tools',
    slug: 'medical-tool',
    parentId: null,
    order: 277,
  },

  // 9.2 Legal & Finance (قانوني ومالي) - 5 types
  {
    nameAr: 'قوالب قانونية',
    nameEn: 'Legal Templates',
    slug: 'legal-template',
    parentId: null,
    order: 278,
  },
  {
    nameAr: 'برمجيات قانونية',
    nameEn: 'Legal Software',
    slug: 'legal-software',
    parentId: null,
    order: 279,
  },
  {
    nameAr: 'قوالب مالية',
    nameEn: 'Financial Templates',
    slug: 'financial-template',
    parentId: null,
    order: 280,
  },
  {
    nameAr: 'برمجيات محاسبية',
    nameEn: 'Accounting Software',
    slug: 'accounting-software',
    parentId: null,
    order: 281,
  },
  {
    nameAr: 'أدوات مالية',
    nameEn: 'Financial Tools',
    slug: 'financial-tool',
    parentId: null,
    order: 282,
  },

  // 9.3 Engineering & Architecture (هندسي ومعماري) - 5 types
  {
    nameAr: 'مخططات هندسية',
    nameEn: 'Engineering Plans',
    slug: 'engineering-plan',
    parentId: null,
    order: 283,
  },
  {
    nameAr: 'قوالب AutoCAD',
    nameEn: 'AutoCAD Templates',
    slug: 'template-autocad',
    parentId: null,
    order: 284,
  },
  {
    nameAr: 'نماذج معمارية',
    nameEn: 'Architectural Models',
    slug: 'architectural-model',
    parentId: null,
    order: 285,
  },
  {
    nameAr: 'برمجيات هندسية',
    nameEn: 'Engineering Software',
    slug: 'engineering-software',
    parentId: null,
    order: 286,
  },
  {
    nameAr: 'أدوات معمارية',
    nameEn: 'Architectural Tools',
    slug: 'architectural-tool',
    parentId: null,
    order: 287,
  },

  // 9.4 Real Estate (عقاري) - 4 types
  {
    nameAr: 'قوالب عقارية',
    nameEn: 'Real Estate Templates',
    slug: 'real-estate-template',
    parentId: null,
    order: 288,
  },
  {
    nameAr: 'برمجيات عقارية',
    nameEn: 'Real Estate Software',
    slug: 'real-estate-software',
    parentId: null,
    order: 289,
  },
  {
    nameAr: 'جولات افتراضية',
    nameEn: 'Virtual Tours',
    slug: 'virtual-tour',
    parentId: null,
    order: 290,
  },
  {
    nameAr: 'أدوات عقارية',
    nameEn: 'Real Estate Tools',
    slug: 'real-estate-tool',
    parentId: null,
    order: 291,
  },

  // 9.5 Education & Training (تعليم وتدريب) - 5 types
  {
    nameAr: 'منصات تعليمية',
    nameEn: 'Learning Platforms',
    slug: 'learning-platform',
    parentId: null,
    order: 292,
  },
  {
    nameAr: 'برمجيات تدريب',
    nameEn: 'Training Software',
    slug: 'training-software',
    parentId: null,
    order: 293,
  },
  {
    nameAr: 'محتوى تدريبي',
    nameEn: 'Training Content',
    slug: 'training-content',
    parentId: null,
    order: 294,
  },
  {
    nameAr: 'أدوات تعليمية',
    nameEn: 'Educational Tools',
    slug: 'educational-tool',
    parentId: null,
    order: 295,
  },
  {
    nameAr: 'برامج إدارة تعلم',
    nameEn: 'Learning Management Systems',
    slug: 'lms',
    parentId: null,
    order: 296,
  },

  // 9.6 Restaurant & Hospitality (مطاعم وضيافة) - 4 types
  {
    nameAr: 'قوالب مطاعم',
    nameEn: 'Restaurant Templates',
    slug: 'restaurant-template',
    parentId: null,
    order: 297,
  },
  {
    nameAr: 'برمجيات مطاعم',
    nameEn: 'Restaurant Software',
    slug: 'restaurant-software',
    parentId: null,
    order: 298,
  },
  {
    nameAr: 'قوالب فنادق',
    nameEn: 'Hotel Templates',
    slug: 'hotel-template',
    parentId: null,
    order: 299,
  },
  {
    nameAr: 'أدوات ضيافة',
    nameEn: 'Hospitality Tools',
    slug: 'hospitality-tool',
    parentId: null,
    order: 300,
  },

  // 9.7 Other Categories (تصنيفات إضافية) - 10 types
  {
    nameAr: 'قوالب تجارة الكترونية',
    nameEn: 'E-Commerce Templates',
    slug: 'ecommerce-template-detailed',
    parentId: null,
    order: 301,
  },
  {
    nameAr: 'محتوى سوشال ميديا',
    nameEn: 'Social Media Content',
    slug: 'social-media-content',
    parentId: null,
    order: 302,
  },
  {
    nameAr: 'أدوات إنتاجية',
    nameEn: 'Productivity Tools',
    slug: 'productivity-tool',
    parentId: null,
    order: 303,
  },
  {
    nameAr: 'ملفات مساعدة',
    nameEn: 'Helper Files',
    slug: 'helper-file',
    parentId: null,
    order: 304,
  },
  {
    nameAr: 'أدوات SEO',
    nameEn: 'SEO Tools',
    slug: 'seo-tool',
    parentId: null,
    order: 305,
  },
  {
    nameAr: 'أدوات أمان',
    nameEn: 'Security Tools',
    slug: 'security-tool',
    parentId: null,
    order: 306,
  },
  {
    nameAr: 'أدوات نسخ احتياطي',
    nameEn: 'Backup Tools',
    slug: 'backup-tool',
    parentId: null,
    order: 307,
  },
  {
    nameAr: 'تراخيص برمجيات',
    nameEn: 'Software Licenses',
    slug: 'software-license',
    parentId: null,
    order: 308,
  },
  {
    nameAr: 'خدمات API',
    nameEn: 'API Services',
    slug: 'api-service',
    parentId: null,
    order: 309,
  },
  {
    nameAr: 'محتوى رقمي متنوع أخر',
    nameEn: 'Other Miscellaneous Digital Content',
    slug: 'other-misc',
    parentId: null,
    order: 310,
  },
]
